services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
#    network_mode: bridge
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /docker/gluetun/data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=#
      - OPENVPN_USER=#
      - OPENVPN_PASSWORD=#
      - SERVER_REGIONS=#
    ports:
#      - 8888:8888/tcp
#      - 8388:8388/tcp
#      - 8388:8388/udp
      - 8000:8000/tcp
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
    restart: always

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Boise
    volumes:
      - /docker/gluetun/qbt:/config
      - /data/torrents:/data/torrents
      - /mnt/corsola/stockpile:/downloads
    depends_on:
      gluetun:
        condition: service_healthy
