- openmeteo:
    label: Boise # optional
    latitude: 43.6150
    longitude: -116.2023
    timezone: America/Boise # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1
- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hourCycle: h23
- resources:
    label: YAMPER
    cpu: true
    memory: true
    disk: /
